### ISSUE TITLE
Cannot user or dismiss footer

### ISSUE THREAD

**Issue by TheTopher** [ThatConference/that.us#154] opened 2020-07-22 18:52 UTC
**Describe the bug**
I don't have profile.  When I tried to favorite a session, a footer-banner appeared telling me that I need to create a profile.  However, the banner is not clickable because of the "Well Hello" pop-up.

**To Reproduce**
1. Go to 'Schedule'
2. Click on 'Favorite' of a card
3. See error

**Expected behavior**
Footer should be clickable (or dismiss the "Well, Hello").

**Screenshots**
<img width="1383" alt="image" src="https://user-images.githubusercontent.com/6912293/88216300-8d4fe800-cc22-11ea-940e-8c8275d5b68c.png">

**Desktop (please complete the following information):**
 - OS: OSX 10.15.4
 - Browser Safari
 - Version 13.1

**Smartphone (please complete the following information):**

**Additional context**

**Comment by csell5** [comment] 2020-07-22 19:03
well I was hoping no one would find that :(

**Comment by csell5** [comment] 2020-07-22 23:45
duplicate of #148

**Closed by csell5** 2020-07-22 23:45 UTC
Labels: bug, duplicate
