### ISSUE TITLE
Ad Blocker, blocking auth cookie on load returning a 500

### ISSUE THREAD

**Issue by csell5** [ThatConference/that.us#1363] opened 2023-03-15 15:45 UTC
**Describe the bug**
[adblocker] seems to be blocking our auth cookie exchange then creating a 500 on the first render.

**To Reproduce**
Load the root page and you should see a redirect, then a 500.

**Comment by csell5** [comment] 2023-03-15 15:46
First found by @agentender

**Comment by AgentEnder** [comment] 2023-03-15 16:11
For some more specifics, this was with: https://chrome.google.com/webstore/detail/crystal-ad-block/lklmhefoneonjalpjcnhaidnodopinib

I have since removed the adblocker from my chrome instance, as it was causing a myriad of issues across multiple websites.

**Comment by csell5** [comment] 2023-03-15 16:13
@AgentEnder, it still shouldn't happen though. It's our cookie.

**Comment by AgentEnder** [comment] 2023-03-15 16:14
Yeah, agreed. I was mainly just providing the link to which ad blocker was impacting this, since I was having issues with other sites and it I feel like it may be a specific to their implementation.

**Comment by csell5** [comment] 2023-03-15 17:53
the other adblocker causing issues https://chrome.google.com/webstore/detail/adblock-plus-free-ad-bloc/cfhdojbkjhnklbpkdaibdccddilifddb

**Comment by brettski** [comment] 2023-03-17 14:23
@csell5 I am able to reproduce this. FYI, this doesn't appear to be an issue on the updated thatconference.com site.

**Comment by brettski** [comment] 2023-03-17 17:48
This error is happening regardless if logged in or not. Testing has shown it is not a cookie-related issue. What appears to be happening is that the ad blockers are matching names to requested filenames, blocking them, which is causing the page to respond 500 (client side generated). Unfortunately sentry.io is blocked as well, though the data being sent to sentry is available in the payload of the request in the network tab. 

### Reproduce theory
Running against `https://that.us` clear out network tab in devTools, turn on ad blocker and navigate to the site. 

The most common file found blocked from that.us is `SocialLink-64ce3039.js` (I am assuming the number part may be different for different builds). If you right click this blocked file in the network tab, you can select to `Block request URL`. This will add it to devTools, Network request blocking section where you can check, and uncheck this file from being blocked.

Now disable the ad blocker, and unsure the URL is unchecked from being blocked. Navigate to that.us to ensure things are working as expected. 

Now check the box for the blocked URL and navigate to the site again. You will see that the site's 500 page is shown. 

The fix for this is to change the base name of this file so it no longer includes `SocialLink`.

Another file being blocked when running the site locally is `/src/routes/_root/upNext.js` Not sure what's matching on that URL.


There is a [StackOverflow](https://stackoverflow.com/questions/17255493/how-to-stop-adblock-plus-blocking-images-in-html-page) article I found on ad blocker plus's site regarding this type of false-positive matches. 


### Now for some good news
Some good news is that the updated site we've been working on, thatconference.com, which is running SvelteKit v1+, etc. isn't affected by this and loads as expected. The `SocialLink` is no longer there/named this. 


### Resolution

As for a resolution to this issue, is we do nothing today as it appears it will be corrected in the next major release version of the site.

**Closed by brettski** 2023-03-17 17:48 UTC
Labels: wontfix, kit
