### ISSUE TITLE
You know what would be nice after creating a session...

### ISSUE THREAD

**Issue by saragibby** [ThatConference/that.us#100] opened 2020-07-17 01:05 UTC
After my session was created I was taken to the schedule page, and had to scroll to find my session. Be nice to go to the detail page for my session after saved. From there it would be cool to have some share ability to copy, link, tweet, bookface, whatever so I can easily spread the word.

**Comment by tsidel** [comment] 2020-07-17 02:17
After I created a session I kind of got a blank screen. Screenshot attached. I came here to add a note that it'd be nice to have some feedback about what I submitted.

It took me to https://that.us/sessions

<img width="600" alt="Screen Shot 2020-07-16 at 9 16 15 PM" src="https://user-images.githubusercontent.com/194128/87741229-9ca9de00-c7a9-11ea-8f0b-76566cc75322.png">

Using Chrome v83
Macbook

**Comment by tsidel** [comment] 2020-07-17 13:46
Might also be a duplicate of #92

**Closed** 2020-07-17 14:47 UTC
Labels: enhancement
